import type { NpcShipConfig, ShipState } from '@/state/types'

export const defaultShipState: ShipState = {
  currentCelestialId: 'planet-1',
  inWarpTransit: false,
  position: [0, 0, 0],
  shieldsUp: false,
  shieldOnlineLevel: 5000,
  shieldRechargeRatePct: 0,
  shield: 5000,
  shieldMax: 5000,
  armor: 4000,
  armorMax: 4000,
  hull: 6000,
  hullMax: 6000,
  capacitor: 800,
  capacitorMax: 800,
  targetSpeed: 0,
  mwdActive: false,
  mwdRemaining: 0,
  mwdCooldownRemaining: 0,
  dampenersActive: true,
  bearing: 0,
  inclination: 0,
  actualHeading: 0,
  actualSpeed: 0,
  actualVelocity: [0, 0, 0],
  actualInclination: 0,
  dacPitch: 0,
  rollAngle: 0,
  thermalSignature: 285,
  radioSignature: -42,
  irstMode: 'BHOT',
  irstSpectrumMode: 'IR',
  laserRange: -1,
  irstZoom: 2,
  irstBearing: 0,
  irstInclination: 0,
  warpCoreAttenuated: false,
  rdneFieldEffect: null,
}

export const defaultNpcShipConfig: NpcShipConfig = {
  behaviorMode: 'manual',
  commandedHeading: 0,
  commandedInclination: 0,
  commandedSpeed: 0,
  mwdActive: false,
  shieldsUp: true,
  radarMode: 'off',
  orbitCenter: [0, 0, 0],
  orbitRadius: 5000,
}
