export const ACCELERATION = 3
export const DECELERATION = 4
export const DAMPENERS_ACCEL_MULT = 6
export const DAMPENERS_DECEL_MULT = 6
export const MWD_SPEED = 800
export const MAX_TURN_RATE = 19.2
export const TURN_ACCEL = 48
export const TURN_RATE_GAIN = 0.288
export const REACTION_DELAY = 0
export const MAX_PITCH_RATE = 6
export const PITCH_ACCEL = 14
export const PITCH_RATE_GAIN = 0.11
export const MAX_ROLL_DEG = 18
export const ROLL_SMOOTH = 5
export const KEY_BEAR_BASE_RATE = 18
export const KEY_BEAR_ACCEL_RATE = 36
export const KEY_BEAR_MAX_RATE = 180
export const KEY_INCL_BASE_RATE = 12
export const KEY_INCL_ACCEL_RATE = 24
export const KEY_INCL_MAX_RATE = 120
export const KEY_SPEED_RATE = 80

/** Peak RDNE-induced acceleration in m/s² on targeted ships at EW forceMagnitude = 1. */
export const RDNE_MAX_ACCEL_MS2 = 54
